@cookie = SESSIONID=ZGMuZGRjNjhkYzktMThjMi00ZWRkLTliNGMtMmZhZGM5Nzg1MmY3LnZmQXp4dWZnRGs4UVBGUVFWZzBQcFE9PQ==;
POST http://localhost:8080/login

{
    "tenant":"dc",
    "username":"root",
    "password":"Aa1234"
}

###

GET http://localhost:8080/check
Cookie: {{cookie}}
###

GET http://localhost:8080/tenant
Set-Cookie: {{cookie}}